### ISSUE TITLE
ConnectToPrismic middleware is causing flash issues

### ISSUE THREAD

**Issue by wrux** [prismicio/php-laravel-starter#1]
I am testing a contact form using this laravel starter and the `\App\Http\Middleware\ConnectToPrismic::class` middleware is causing issues with flash messages for validation. 

If I disable this code:

```
$request['api'] = Api::get(
    config('prismic.url'),
    config('prismic.token')
);
```

Data validation errors seem to work but once I re-enable this then it will stop working. I have tested `session()->flash('flash_message', 'test');` in my code before rendering the page view and flash messages seem to work this way but I cannot work out why flash messages are not working properly. 

I have tried to rename api to prismic_api like below but it is still not working:

```
$request['prismic_api'] = Api::get(
    config('prismic.url'),
    config('prismic.token')
);
```

Any ideas for this?

**Comment by levimykel** [comment]
Hi @wrux, sorry for the delay on this. I'll let the dev team know about this and add it to their backlog. Thanks for reporting it.
